In [43]:
import pandas as pd
df = pd.read_csv("data_cleaning_sample.csv")

In [44]:
df

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [45]:
df.isnull()  # in output table where there is True at those p[laces in data set we can understand that no value or object is present

    Name    Age   City  Gender  Email  Join Date
0  False  False  False   False  False      False
1  False   True  False   False  False      False
2  False  False  False   False  False      False
3  False   True  False   False  False      False
4  False  False  False   False  False      False
5   True  False  False   False  False       True
6  False  False  False   False  False      False
7  False  False  False   False  False      False
8  False   True  False   False  False      False

In [46]:
df.isnull().sum()   # Tells number of missing values present in each column

Name         1
Age          3
City         0
Gender       0
Email        0
Join Date    1
dtype: int64

In [47]:
df.dropna()   # it drops all the rows which have something missing and only gives rows which have all the values present

    Name   Age         City Gender              Email   Join Date
0  Alice  25.0     New York      F  alice@example.com  01-05-2021
2    Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
4  David  22.0       Mumbai      M  david@example.com  12-11-2019
6  Alice  25.0     New York      F  alice@example.com  01-05-2021
7  Alice  25.0     New York      F  alice@example.com  01-05-2021

In [48]:
df.dropna(axis=1)  # here dropped a column and this is mainly used in machine learning where there are around 50 types and you dont want those many types to be used

          City Gender              Email
0     New York      F  alice@example.com
1        Delhi      M    charlie@example
2  Los Angeles      M    bob@example.com
3        Delhi      M    charlie@example
4       Mumbai      M  david@example.com
5        Delhi      F     eve@domain.com
6     New York      F  alice@example.com
7     New York      F  alice@example.com
8        Delhi      M    charlie@example

## Difference between 
### df.drop(to_drop, axis = 1)
### df.drop(to_drop, inplace = True,axis = 1)
## is that in inplace one it do changes in original df but without inplace it returns new dataframe so if we want to continue in doing it we can store it in new dataframe like df2

In [49]:
to_drop =['Email','Age']
df.drop(to_drop, axis = 1)
## df.drop(columns=to_drop, inplace=True) instead of axis = 1 we can directly mention columns and remove it

      Name         City Gender   Join Date
0    Alice     New York      F  01-05-2021
1  Charlie        Delhi      M  20-07-2021
2      Bob  Los Angeles      M  15-06-2020
3  Charlie        Delhi      M  20-07-2021
4    David       Mumbai      M  12-11-2019
5      NaN        Delhi      F         NaN
6    Alice     New York      F  01-05-2021
7    Alice     New York      F  01-05-2021
8  Charlie        Delhi      M  20-07-2021

In [50]:
df

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [51]:
df.fillna(0)  # In places where Nan is present we change it to 0 it is done in a copy not in actual df changes

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   0.0        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   0.0        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5        0  28.0        Delhi      F     eve@domain.com           0
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   0.0        Delhi      M    charlie@example  20-07-2021

In [52]:
df["Age"].fillna(df["Age"].mean())   # What it does is that in places of Nan in age column it replaces it with mean

0    25.000000
1    25.833333
2    30.000000
3    25.833333
4    22.000000
5    28.000000
6    25.000000
7    25.000000
8    25.833333
Name: Age, dtype: float64

In [53]:
df.fillna(method = "ffill") # Forward Fill means if 3rd is Nan then it will take same value of 2nd 
# or use df.ffill()

C:\Users\Nilesh\AppData\Local\Temp\ipykernel_63040\3136771938.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method = "ffill") # Forward Fill means if 3rd is Nan then it will take same value of 2nd

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie  25.0        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie  30.0        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5    David  28.0        Delhi      F     eve@domain.com  12-11-2019
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie  25.0        Delhi      M    charlie@example  20-07-2021

In [54]:
df.bfill() # df.fillna(method="bfill")

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie  30.0        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie  22.0        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5    Alice  28.0        Delhi      F     eve@domain.com  01-05-2021
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [57]:
index = ['A','B','C','D','E','F','G','H','I']
df1 = df.copy()          # assign dataframe here if we dont use copy() it do changes to original one
df1.index = index # set new index
df1

      Name   Age         City Gender              Email   Join Date
A    Alice  25.0     New York      F  alice@example.com  01-05-2021
B  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
C      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
D  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
E    David  22.0       Mumbai      M  david@example.com  12-11-2019
F      NaN  28.0        Delhi      F     eve@domain.com         NaN
G    Alice  25.0     New York      F  alice@example.com  01-05-2021
H    Alice  25.0     New York      F  alice@example.com  01-05-2021
I  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [58]:
df

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [59]:
df.duplicated()

0    False
1    False
2    False
3     True
4    False
5    False
6     True
7     True
8     True
dtype: bool

In [61]:
df.drop_duplicates()

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN

In [62]:
df.duplicated(subset=["Name","Age"])

0    False
1    False
2    False
3     True
4    False
5    False
6     True
7     True
8     True
dtype: bool

In [64]:
df["Name"].str.lower()

0      alice
1    charlie
2        bob
3    charlie
4      david
5        NaN
6      alice
7      alice
8    charlie
Name: Name, dtype: object

In [68]:
df["City"].str.contains("delhi", case=False)

0    False
1     True
2    False
3     True
4    False
5     True
6    False
7    False
8     True
Name: City, dtype: bool

In [69]:
type(df["City"].str.contains("delhi", case=False))

pandas.core.series.Series

In [72]:
df["Email"].str.split("@")

0    [alice, example.com]
1      [charlie, example]
2      [bob, example.com]
3      [charlie, example]
4    [david, example.com]
5       [eve, domain.com]
6    [alice, example.com]
7    [alice, example.com]
8      [charlie, example]
Name: Email, dtype: object

In [73]:
df["Email"].str.split("@")[0]

['alice', 'example.com']

In [75]:
type(df["Email"].str.split("@")[0])

list

In [77]:
df2 = df.dropna().copy()

In [79]:
df2["Age"] = df2["Age"].astype(int)

In [80]:
df2

    Name  Age         City Gender              Email   Join Date
0  Alice   25     New York      F  alice@example.com  01-05-2021
2    Bob   30  Los Angeles      M    bob@example.com  15-06-2020
4  David   22       Mumbai      M  david@example.com  12-11-2019
6  Alice   25     New York      F  alice@example.com  01-05-2021
7  Alice   25     New York      F  alice@example.com  01-05-2021

In [81]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, 0 to 7
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Name       5 non-null      object
 1   Age        5 non-null      int64
 2   City       5 non-null      object
 3   Gender     5 non-null      object
 4   Email      5 non-null      object
 5   Join Date  5 non-null      object
dtypes: int64(1), object(5)
memory usage: 280.0+ bytes

In [82]:
df2.head()

    Name  Age         City Gender              Email   Join Date
0  Alice   25     New York      F  alice@example.com  01-05-2021
2    Bob   30  Los Angeles      M    bob@example.com  15-06-2020
4  David   22       Mumbai      M  david@example.com  12-11-2019
6  Alice   25     New York      F  alice@example.com  01-05-2021
7  Alice   25     New York      F  alice@example.com  01-05-2021

In [83]:
df2.head(1)

    Name  Age      City Gender              Email   Join Date
0  Alice   25  New York      F  alice@example.com  01-05-2021

In [84]:
df

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [85]:
df2

    Name  Age         City Gender              Email   Join Date
0  Alice   25     New York      F  alice@example.com  01-05-2021
2    Bob   30  Los Angeles      M    bob@example.com  15-06-2020
4  David   22       Mumbai      M  david@example.com  12-11-2019
6  Alice   25     New York      F  alice@example.com  01-05-2021
7  Alice   25     New York      F  alice@example.com  01-05-2021

In [86]:
df2["Age Group"] = df2["Age"].apply(lambda x: "Adult" if x>=18 else "Minor")

In [87]:
df2

    Name  Age         City Gender              Email   Join Date Age Group
0  Alice   25     New York      F  alice@example.com  01-05-2021     Adult
2    Bob   30  Los Angeles      M    bob@example.com  15-06-2020     Adult
4  David   22       Mumbai      M  david@example.com  12-11-2019     Adult
6  Alice   25     New York      F  alice@example.com  01-05-2021     Adult
7  Alice   25     New York      F  alice@example.com  01-05-2021     Adult

In [88]:
df2["Age Group"] = df2["Age"].apply(lambda x: "Adult" if x>=25 else "Minor")

In [89]:
df2

    Name  Age         City Gender              Email   Join Date Age Group
0  Alice   25     New York      F  alice@example.com  01-05-2021     Adult
2    Bob   30  Los Angeles      M    bob@example.com  15-06-2020     Adult
4  David   22       Mumbai      M  david@example.com  12-11-2019     Minor
6  Alice   25     New York      F  alice@example.com  01-05-2021     Adult
7  Alice   25     New York      F  alice@example.com  01-05-2021     Adult

In [92]:
def isminor(x):
    return "Adult" if x>=30 else "Minor"
df2["Age Group"] = df2["Age"].apply(isminor)

In [93]:
df2

    Name  Age         City Gender              Email   Join Date Age Group
0  Alice   25     New York      F  alice@example.com  01-05-2021     Minor
2    Bob   30  Los Angeles      M    bob@example.com  15-06-2020     Adult
4  David   22       Mumbai      M  david@example.com  12-11-2019     Minor
6  Alice   25     New York      F  alice@example.com  01-05-2021     Minor
7  Alice   25     New York      F  alice@example.com  01-05-2021     Minor

In [104]:
gender_map = {"M":"Male","F":"Female","O":"Other"}
df2["Gender"] = df2["Gender"].map(gender_map)

In [105]:
df2

    Name  Age         City Gender              Email   Join Date Age Group
0  Alice   25     New York    NaN  alice@example.com  01-05-2021     Minor
2    Bob   30  Los Angeles    NaN    bob@example.com  15-06-2020     Adult
4  David   22       Mumbai    NaN  david@example.com  12-11-2019     Minor
6  Alice   25     New York    NaN  alice@example.com  01-05-2021     Minor
7  Alice   25     New York    NaN  alice@example.com  01-05-2021     Minor

In [108]:
df2["City"].replace({"Delhi": "New Delhi","Mumbai": "New Mumbai"})
df2

    Name  Age         City Gender              Email   Join Date Age Group
0  Alice   25     New York    NaN  alice@example.com  01-05-2021     Minor
2    Bob   30  Los Angeles    NaN    bob@example.com  15-06-2020     Adult
4  David   22       Mumbai    NaN  david@example.com  12-11-2019     Minor
6  Alice   25     New York    NaN  alice@example.com  01-05-2021     Minor
7  Alice   25     New York    NaN  alice@example.com  01-05-2021     Minor