In [1]:
import pandas as pd

In [2]:
employees = pd.DataFrame({
    "EmpID": [1, 2, 3],
    "Name": ["Alice", "Bob", "Charlie"],
    "DeptID": [10, 20, 30]
})

departments = pd.DataFrame({
    "DeptID": [10, 20, 40],
    "DeptName": ["HR", "Engineering", "Marketing"]
})

In [3]:
employees

   EmpID     Name  DeptID
0      1    Alice      10
1      2      Bob      20
2      3  Charlie      30

In [4]:
departments

   DeptID     DeptName
0      10           HR
1      20  Engineering
2      40    Marketing

In [6]:
pd.merge(employees,departments, on="DeptID") # Ineer Join it skips the rows which are not common like in DEPTID it skipped 30 and 40 as they are not common in opposite of respective Dataframe

   EmpID   Name  DeptID     DeptName
0      1  Alice      10           HR
1      2    Bob      20  Engineering

In [12]:
pd.merge(employees,departments, on = "DeptID",how = "left") # LEft Join because it contains all of employees like DeptID 30 whose name element will be NaN

   EmpID     Name  DeptID     DeptName
0      1    Alice      10           HR
1      2      Bob      20  Engineering
2      3  Charlie      30          NaN

In [14]:
pd.merge(employees,departments, on = "DeptID", how = "right")  # Right Join

   EmpID   Name  DeptID     DeptName
0    1.0  Alice      10           HR
1    2.0    Bob      20  Engineering
2    NaN    NaN      40    Marketing

In [15]:
pd.merge(employees,departments,on = "DeptID", how = "outer") # Outer Join will show content of both dataframes and where data is missing it shows NaN

   EmpID     Name  DeptID     DeptName
0    1.0    Alice      10           HR
1    2.0      Bob      20  Engineering
2    3.0  Charlie      30          NaN
3    NaN      NaN      40    Marketing

In [18]:
df1 = pd.DataFrame({"Name":["Alice","Bob"]})
df2 = pd.DataFrame({"Name":["Charlie","David"]})

In [19]:
df1

    Name
0  Alice
1    Bob

In [20]:
df2

      Name
0  Charlie
1    David

In [23]:
pd.concat([df1,df2])

      Name
0    Alice
1      Bob
0  Charlie
1    David

In [24]:
pd.concat([df1,df2], axis = 1)

    Name     Name
0  Alice  Charlie
1    Bob    David

In [25]:
df3 = pd.DataFrame({"Name":["Alice","Bob"],"score":[98,59]})
df4 = pd.DataFrame({"Name":["Charlie","David"],"Age":[21,19]})

In [26]:
df3

    Name  score
0  Alice     98
1    Bob     59

In [27]:
df4

      Name  Age
0  Charlie   21
1    David   19

In [28]:
pd.concat([df3,df4])

      Name  score   Age
0    Alice   98.0   NaN
1      Bob   59.0   NaN
0  Charlie    NaN  21.0
1    David    NaN  19.0

In [29]:
pd.concat([df3,df4],axis = 1)

    Name  score     Name  Age
0  Alice     98  Charlie   21
1    Bob     59    David   19